{% set name = "traffix" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/traffix-{{ version }}.tar.gz
  sha256: 5b17b005389931d5c5770122faa44ae1cd6064ebc14ab60227ff93afcd5bd323

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - osmnx >=1.3.0
    - pandas >=1.5
    - geopandas >=0.12
    - matplotlib-base >=3.5
    - networkx >=2.8
    - numpy >=1.23
    - pyproj >=3.4
    - requests >=2.28
    - shapely >=2.0
    - openpyxl

test:
  imports:
    - traffix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ultios/traffix
  summary: A package for macroscopic transportation assignment.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Ultios
